# Generated by Django 4.2.11 on 2024-07-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_aemployeeid_alter_item_btype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='baddess',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
