# Generated by Django 4.2.11 on 2024-07-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_baddess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='gradshoolname',
            new_name='gradschoolname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='tershoolname',
            new_name='terschoolname',
        ),
    ]
